/**
 * バッチ01: 追加20本モック（runMode: mock_preview 固定）
 * `demo-batches/index.ts` で `nextMockDemos` に結合される。
 *
 * キー順: title, slug, industry, inputType, runMode, sampleData, outputStructure,
 * mockOutputPrimary, mockOutputSecondary, ctaTitle, ctaButtonText, description,
 * functionTags, industryTags, moduleTags, oneLiner, inputPlaceholder, systemPrompt
 */

export const batch01NextMockDemos = [
  {
    _type: "aiDemo" as const,
    title: "ヒヤリハット是正プラン生成",
    slug: { _type: "slug" as const, current: "near-miss-correction-plan" },
    industry: "construction",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "ヒヤリハットの内容を入力してください",
    mockOutputPrimary: `## 1. 是正指示書\n\n- 事象: 足場手すりゆるみ\n- 是正内容: 補修完了まで該当箇所の作業中止\n- 担当: 外壁工事 〇〇社\n- 期限: 明日12時`,
    mockOutputSecondary: `## 2. 朝礼共有文\n\n本日〇〇現場で足場手すりゆるみを確認。補修完了まで該当箇所での作業を中止します。`,
    systemPrompt: "あなたはヒヤリハットの是正プランを生成するアシスタントです。",
    outputStructure: "是正指示書と朝礼共有文の2セクションで出力すること。",
    sampleData: [
      "足場の手すりがゆるんでいた。作業員が気づいて報告",
      "養生シートが剥がれていた。雨予報なので至急対応",
      "資材の置き場が通路を塞いでいた。搬入後すぐに整理",
    ],
    ctaTitle: "あなたの安全フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "ヒヤリハット報告から是正指示書と朝礼共有文を即生成。安全対策の記録業務を効率化します。",
    industryTags: ["建設"],
    functionTags: ["安全管理", "報告書生成"],
    moduleTags: ["LLM"],
    oneLiner: "ヒヤリハットから是正プランを即生成",
  },
  {
    _type: "aiDemo" as const,
    title: "雨天時の工程リスケ案",
    slug: { _type: "slug" as const, current: "rain-schedule-reschedule" },
    industry: "construction",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "雨天影響の内容を入力してください",
    mockOutputPrimary: `## 1. 工程変更案\n\n- 本日: 外壁塗装→屋内作業（内装下地）に振替\n- 明日: 天候回復見込み。外壁塗装再開\n- 影響: 納期変更なし`,
    mockOutputSecondary: `## 2. 関係者連絡文\n\n本日雨天のため外壁塗装を屋内作業に振替ました。明日再開予定です。`,
    systemPrompt: "あなたは雨天時の工程リスケ案を生成するアシスタントです。",
    outputStructure: "工程変更案と関係者連絡文の2セクションで出力すること。",
    sampleData: [
      "明日も雨予報。外壁塗装が2日遅れそう。屋内作業に振替たい",
      "本日午後から雨。コンクリート打設を明日に延期",
      "週末雨で足場作業中止。月曜に繰越",
    ],
    ctaTitle: "あなたの工程フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "雨天影響から工程変更案と関係者連絡文を即生成。現場の調整業務を効率化します。",
    industryTags: ["建設"],
    functionTags: ["工程調整", "連絡文生成"],
    moduleTags: ["LLM"],
    oneLiner: "雨天影響から工程リスケ案を即生成",
  },
  {
    _type: "aiDemo" as const,
    title: "現場コスト異常検知メモ",
    slug: { _type: "slug" as const, current: "site-cost-anomaly-memo" },
    industry: "construction",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "コスト数値や気になる点を入力してください",
    mockOutputPrimary: `## 1. 異常要因サマリ\n\n- 資材費: 前月比+15%。鋼材価格上昇\n- 外注費: 想定内\n- 人件費: 残業増（工程遅延のため）`,
    mockOutputSecondary: `## 2. 対応タスク表\n\n1. 鋼材仕入先の相見積もり\n2. 残業抑制のため工程見直し\n3. 来月予算の再試算`,
    systemPrompt: "あなたは現場コストの異常検知メモを生成するアシスタントです。",
    outputStructure: "異常要因サマリと対応タスク表の2セクションで出力すること。",
    sampleData: [
      "今月の資材費が予算比20%オーバー。鋼材が高騰",
      "外注費は想定内だが人件費が増えている。残業多め",
      "A棟の原価がB棟より15%高い。原因を整理したい",
    ],
    ctaTitle: "あなたの原価フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "コスト数値から異常要因と対応タスクを即整理。原価管理の負荷を軽減します。",
    industryTags: ["建設"],
    functionTags: ["原価管理", "要約"],
    moduleTags: ["LLM"],
    oneLiner: "コスト異常から要因と対応タスクを即整理",
  },
  {
    _type: "aiDemo" as const,
    title: "協力会社評価コメント下書き",
    slug: { _type: "slug" as const, current: "subcontractor-eval-draft" },
    industry: "construction",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "協力会社の評価ポイントを入力してください",
    mockOutputPrimary: `## 1. 評価シート文案\n\n- 工程遵守: 良好。納期厳守\n- 品質: 問題なし。養生も適切\n- 安全: ヒヤリハット1件。是正済み\n- 総合: B評価`,
    mockOutputSecondary: `## 2. 改善依頼文\n\n次期以降、足場点検の事前チェックを強化してください。`,
    systemPrompt: "あなたは協力会社評価のコメント下書きを生成するアシスタントです。",
    outputStructure: "評価シート文案と改善依頼文の2セクションで出力すること。",
    sampleData: [
      "〇〇社は工程も品質も問題なし。安全で1件ヒヤリハット",
      "△△社は納期遅れが2回。品質は良好",
      "□□社は初めての協力。丁寧な作業で好印象",
    ],
    ctaTitle: "あなたの評価フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "評価ポイントから評価シート文案と改善依頼文を即生成。協力会社管理を効率化します。",
    industryTags: ["建設"],
    functionTags: ["協力会社管理", "評価"],
    moduleTags: ["LLM"],
    oneLiner: "評価ポイントから評価コメントを即生成",
  },
  {
    _type: "aiDemo" as const,
    title: "申請・更新期限アラート整理",
    slug: { _type: "slug" as const, current: "deadline-alert-organizer" },
    industry: "legal",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "期限が気になる申請・契約を入力してください",
    mockOutputPrimary: `## 1. 期限一覧\n\n- 〇〇許認可: 2025/4/30 更新申請\n- △△契約: 2025/5/15 解約通知期限\n- □□届出: 2025/4/10 提出期限`,
    mockOutputSecondary: `## 2. リマインド文面\n\n〇〇許認可の更新申請が4月末です。必要書類の準備を開始してください。`,
    systemPrompt: "あなたは申請・更新期限のアラート整理をするアシスタントです。",
    outputStructure: "期限一覧とリマインド文面の2セクションで出力すること。",
    sampleData: [
      "建設業許可の更新が来月。書類揃えたい",
      "業務委託契約の解約通知が60日前まで",
      "法人登記の変更届を忘れずに",
    ],
    ctaTitle: "あなたの期限管理フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "期限情報から一覧とリマインド文を即整理。期限管理の見落としを防ぎます。",
    industryTags: ["士業", "建設", "製造"],
    functionTags: ["期限管理", "要約"],
    moduleTags: ["LLM"],
    oneLiner: "期限情報から一覧とリマインドを即整理",
  },
  {
    _type: "aiDemo" as const,
    title: "契約修正提案ドラフト",
    slug: { _type: "slug" as const, current: "contract-amendment-draft" },
    industry: "legal",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "修正したい条項や懸念点を入力してください",
    mockOutputPrimary: `## 1. 修正条項案\n\n- 第〇条（解約）: 90日前に書面通知に変更\n- 第△条（責任制限）: 直接損害に限定を明記\n- 第□条（秘密保持）: 契約終了後3年に延長`,
    mockOutputSecondary: `## 2. 相手方送付文\n\n契約書の一部条項について修正をご提案したく、別紙のとおり案を送付します。ご検討のほどよろしくお願いいたします。`,
    systemPrompt: "あなたは契約修正の提案ドラフトを生成するアシスタントです。",
    outputStructure: "修正条項案と相手方送付文の2セクションで出力すること。",
    sampleData: [
      "解約条項を90日前通知に変更したい",
      "責任制限を直接損害に限定したい",
      "秘密保持期間を3年に延長したい",
    ],
    ctaTitle: "まずは1契約で無料レビューを実施します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "修正希望から条項案と送付文を即生成。契約交渉の準備を効率化します。",
    industryTags: ["士業", "製造"],
    functionTags: ["契約交渉", "文書生成"],
    moduleTags: ["LLM"],
    oneLiner: "修正希望から契約修正案を即生成",
  },
  {
    _type: "aiDemo" as const,
    title: "初回相談ヒアリング設計",
    slug: { _type: "slug" as const, current: "first-consult-hearing-design" },
    industry: "legal",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "相談の種類・想定クライアントを入力してください",
    mockOutputPrimary: `## 1. 質問リスト\n\n1. ご依頼の経緯と背景\n2. 希望するゴール・期限\n3. 予算感・スコープ\n4. 関係者の人数・役割\n5. 過去の類似案件の有無`,
    mockOutputSecondary: `## 2. 面談メモ雛形\n\n- 日時:\n- 参加者:\n- 主な発言:\n- 次回アクション:`,
    systemPrompt: "あなたは初回相談のヒアリング設計をするアシスタントです。",
    outputStructure: "質問リストと面談メモ雛形の2セクションで出力すること。",
    sampleData: [
      "M&Aの初回相談。売り手企業向け",
      "労務トラブルの初回相談。従業員50名規模",
      "知的財産の相談。スタートアップ向け",
    ],
    ctaTitle: "あなたのヒアリングフォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "相談種別から質問リストとメモ雛形を即生成。初回面談の準備を効率化します。",
    industryTags: ["士業"],
    functionTags: ["面談準備", "ヒアリング"],
    moduleTags: ["LLM"],
    oneLiner: "相談種別からヒアリング設計を即生成",
  },
  {
    _type: "aiDemo" as const,
    title: "月次請求チェック補助",
    slug: { _type: "slug" as const, current: "monthly-billing-check" },
    industry: "legal",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "請求内容や差分の要点を入力してください",
    mockOutputPrimary: `## 1. 請求差分一覧\n\n- 案件A: 前月比+5時間。追加作業分\n- 案件B: 変更なし\n- 案件C: 未請求2件。今月に計上`,
    mockOutputSecondary: `## 2. 修正依頼文\n\n案件Aについて追加作業5時間分を請求書に反映してください。案件Cの2件は今月分に含めてください。`,
    systemPrompt: "あなたは月次請求のチェック補助をするアシスタントです。",
    outputStructure: "請求差分一覧と修正依頼文の2セクションで出力すること。",
    sampleData: [
      "今月の請求。A案件で5時間追加。Bは据置",
      "未請求が2件ある。今月にまとめて請求したい",
      "前月と比較して時間数が増えている。理由を確認",
    ],
    ctaTitle: "あなたの請求フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "請求情報から差分一覧と修正依頼を即整理。請求管理のミスを防ぎます。",
    industryTags: ["士業", "製造"],
    functionTags: ["請求管理", "要約"],
    moduleTags: ["LLM"],
    oneLiner: "請求情報から差分と修正依頼を即整理",
  },
  {
    _type: "aiDemo" as const,
    title: "不良報告の原因仮説整理",
    slug: { _type: "slug" as const, current: "defect-cause-hypothesis" },
    industry: "manufacturing",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "不良内容・状況を入力してください",
    mockOutputPrimary: `## 1. 原因仮説表\n\n- 人: 作業手順の理解不足の可能性\n- 機: 治具の摩耗・設定ずれ\n- 料: ロット差・保管条件\n- 法: 検査基準の曖昧さ`,
    mockOutputSecondary: `## 2. 再発防止案\n\n1. 作業手順の見直しと教育\n2. 治具の定期点検頻度を上げる\n3. 初物検査の強化`,
    systemPrompt: "あなたは不良報告の原因仮説を整理するアシスタントです。",
    outputStructure: "原因仮説表と再発防止案の2セクションで出力すること。",
    sampleData: [
      "寸法不良が5件。同じ治具を使っている",
      "外観不良。作業者によって発生率が違う",
      "異物混入。原料ロットを確認したい",
    ],
    ctaTitle: "あなたの品質フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "不良報告から原因仮説と再発防止案を即整理。品質改善の検討を効率化します。",
    industryTags: ["製造"],
    functionTags: ["品質管理", "要約"],
    moduleTags: ["LLM"],
    oneLiner: "不良報告から原因仮説を即整理",
  },
  {
    _type: "aiDemo" as const,
    title: "設備点検チェック項目生成",
    slug: { _type: "slug" as const, current: "equipment-inspection-checklist" },
    industry: "manufacturing",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "設備名・点検種別を入力してください",
    mockOutputPrimary: `## 1. 点検チェックリスト\n\n- 油量・油質\n- 異音・振動\n- 漏れ（油・空気）\n- 安全ガードの作動\n- 表示灯・警報\n- 清掃状態`,
    mockOutputSecondary: `## 2. 作業指示\n\n点検は稼働停止後、安全確認のうえ実施。異常時は即停止し報告すること。`,
    systemPrompt: "あなたは設備点検のチェック項目を生成するアシスタントです。",
    outputStructure: "点検チェックリストと作業指示の2セクションで出力すること。",
    sampleData: [
      "プレス機の日次点検",
      "CNCの週次点検",
      "ボイラーの月次点検",
    ],
    ctaTitle: "あなたの点検フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "設備情報から点検チェック項目と作業指示を即生成。保全業務を効率化します。",
    industryTags: ["製造", "建設"],
    functionTags: ["保全", "チェックリスト"],
    moduleTags: ["LLM"],
    oneLiner: "設備から点検チェック項目を即生成",
  },
  {
    _type: "aiDemo" as const,
    title: "在庫偏り是正提案",
    slug: { _type: "slug" as const, current: "inventory-balance-proposal" },
    industry: "manufacturing",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "在庫状況・偏りの内容を入力してください",
    mockOutputPrimary: `## 1. 在庫調整案\n\n- A品: 過剰。他倉庫へ移管または出荷促進\n- B品: 不足。発注前倒し推奨\n- C品: 適正。現状維持`,
    mockOutputSecondary: `## 2. 発注修正案\n\nA品: 次回発注を2週間延期\nB品: 発注量を1.5倍に増量`,
    systemPrompt: "あなたは在庫偏りの是正提案をするアシスタントです。",
    outputStructure: "在庫調整案と発注修正案の2セクションで出力すること。",
    sampleData: [
      "A品が過剰。B品が不足気味",
      "倉庫間で偏りがある。移管したい",
      "月末在庫が予想より多い。出荷促進を検討",
    ],
    ctaTitle: "あなたの在庫フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "在庫状況から調整案と発注修正を即提案。在庫管理を効率化します。",
    industryTags: ["製造", "小売"],
    functionTags: ["在庫管理", "要約"],
    moduleTags: ["LLM"],
    oneLiner: "在庫偏りから是正提案を即生成",
  },
  {
    _type: "aiDemo" as const,
    title: "シフト引継ぎサマリ生成",
    slug: { _type: "slug" as const, current: "shift-handover-summary" },
    industry: "manufacturing",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "シフト中の出来事・残作業を入力してください",
    mockOutputPrimary: `## 1. 引継ぎ要約\n\n- 稼働: 通常。停止なし\n- 不良: 2件。対応済み\n- 残作業: ロット123の最終検査\n- 注意: 機械Aの異音。要点検`,
    mockOutputSecondary: `## 2. 優先対応一覧\n\n1. ロット123の最終検査\n2. 機械Aの点検依頼`,
    systemPrompt: "あなたはシフト引継ぎのサマリを生成するアシスタントです。",
    outputStructure: "引継ぎ要約と優先対応一覧の2セクションで出力すること。",
    sampleData: [
      "不良2件対応済み。ロット123が残り。機械Aが少し音がする",
      "ライン停止30分。復旧済み。在庫は問題なし",
      "新人OJT実施。明日も継続。特記事項なし",
    ],
    ctaTitle: "あなたの引継ぎフォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "シフト内容から引継ぎ要約と優先対応を即生成。引継ぎ業務を効率化します。",
    industryTags: ["製造", "小売", "医療"],
    functionTags: ["引継ぎ", "要約"],
    moduleTags: ["LLM"],
    oneLiner: "シフト内容から引継ぎサマリを即生成",
  },
  {
    _type: "aiDemo" as const,
    title: "レビューから改善案抽出",
    slug: { _type: "slug" as const, current: "review-improvement-extract" },
    industry: "manufacturing",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "商品レビューやフィードバックを入力してください",
    mockOutputPrimary: `## 1. 改善優先度表\n\n- 梱包: 高。破損指摘多数\n- サイズ感: 中。表記の見直し\n- 品質: 低。概ね良好`,
    mockOutputSecondary: `## 2. 商品説明修正文\n\n「丁寧な梱包」→「二重梱包で破損防止」など、具体的な訴求に変更を推奨。`,
    systemPrompt: "あなたはレビューから改善案を抽出するアシスタントです。",
    outputStructure: "改善優先度表と商品説明修正文の2セクションで出力すること。",
    sampleData: [
      "梱包の破損が多い。サイズが思ったより小さいとの声",
      "品質は良いが届くのが遅い。説明が分かりにくい",
      "色のイメージと違う。写真を増やしてほしい",
    ],
    ctaTitle: "あなたの分析フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "レビューから改善優先度と商品説明修正案を即抽出。商品改善を効率化します。",
    industryTags: ["小売", "EC", "製造"],
    functionTags: ["商品企画", "要約"],
    moduleTags: ["LLM"],
    oneLiner: "レビューから改善案を即抽出",
  },
  {
    _type: "aiDemo" as const,
    title: "キャンペーン訴求文AB案",
    slug: { _type: "slug" as const, current: "campaign-copy-ab" },
    industry: "manufacturing",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "キャンペーン内容・対象・目的を入力してください",
    mockOutputPrimary: `## 1. LP訴求文2案\n\nA案: 「今だけ30%OFF。在庫限り」\nB案: 「春の大感謝祭。お得な3点セット」`,
    mockOutputSecondary: `## 2. 店頭POP文案\n\n「春の大感謝祭 本日限定」\n「〇〇シリーズ まとめ買いでお得」`,
    systemPrompt: "あなたはキャンペーン訴求文のAB案を生成するアシスタントです。",
    outputStructure: "LP訴求文2案と店頭POP文案の2セクションで出力すること。",
    sampleData: [
      "春の感謝祭。30%OFF。LPと店頭POP用",
      "新商品リリース。ECと実店舗で訴求",
      "在庫一掃セール。期限感を出したい",
    ],
    ctaTitle: "あなたの訴求フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "キャンペーン情報から訴求文AB案とPOP文案を即生成。販促制作を効率化します。",
    industryTags: ["小売", "EC"],
    functionTags: ["販促", "文書生成"],
    moduleTags: ["LLM"],
    oneLiner: "キャンペーンから訴求文AB案を即生成",
  },
  {
    _type: "aiDemo" as const,
    title: "返品理由の分類と対策",
    slug: { _type: "slug" as const, current: "return-reason-classification" },
    industry: "manufacturing",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "返品理由や傾向を入力してください",
    mockOutputPrimary: `## 1. 理由分類表\n\n- サイズ不合: 35%。表記の見直し推奨\n- イメージ違い: 25%。写真・説明の強化\n- 不良: 15%。品質チェック強化\n- その他: 25%`,
    mockOutputSecondary: `## 2. FAQ改善案\n\n「サイズの選び方」を詳細化。実寸表を追加。`,
    systemPrompt: "あなたは返品理由の分類と対策を整理するアシスタントです。",
    outputStructure: "理由分類表とFAQ改善案の2セクションで出力すること。",
    sampleData: [
      "返品理由でサイズ不合が多い。イメージ違いも",
      "不良での返品が増えている。梱包を疑う",
      "色のイメージ違い。写真を増やしたい",
    ],
    ctaTitle: "あなたの分析フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "返品理由から分類とFAQ改善案を即整理。CS効率化と返品削減に貢献します。",
    industryTags: ["小売", "EC"],
    functionTags: ["CS効率化", "要約"],
    moduleTags: ["LLM"],
    oneLiner: "返品理由から分類と対策を即整理",
  },
  {
    _type: "aiDemo" as const,
    title: "物件内見メモ自動整理",
    slug: { _type: "slug" as const, current: "property-viewing-memo" },
    industry: "legal",
    inputType: "audio_text" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "内見の音声を録音するか、要点をテキストで入力してください",
    mockOutputPrimary: `## 1. 内見サマリ\n\n- 立地: 駅徒歩5分。静か\n- 室内: キッチン広い。収納十分\n- 気になる点: 窓の結露。築年数\n- 顧客反応: 前向き`,
    mockOutputSecondary: `## 2. 次アクション\n\n1. 築年数・修繕履歴の確認\n2. 翌日フォローメール送付`,
    systemPrompt: "あなたは物件内見メモを自動整理するアシスタントです。",
    outputStructure: "内見サマリと次アクションの2セクションで出力すること。",
    sampleData: [
      "駅徒歩5分。キッチンが広くて好印象。窓の結露が気になるとのこと",
      "立地は良いが騒音が心配。収納は十分",
      "築浅で綺麗。価格交渉の余地を探りたい",
    ],
    ctaTitle: "あなたの内見フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "内見内容からサマリと次アクションを即整理。不動産営業の記録業務を効率化します。",
    industryTags: ["不動産", "士業"],
    functionTags: ["音声入力", "案件整理"],
    moduleTags: ["Whisper", "LLM"],
    oneLiner: "内見内容からメモを即整理",
  },
  {
    _type: "aiDemo" as const,
    title: "内見後フォローメール下書き",
    slug: { _type: "slug" as const, current: "post-viewing-followup-mail" },
    industry: "legal",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "内見の反応・気になった点を入力してください",
    mockOutputPrimary: `## 1. 顧客向け文面\n\n本日はお越しいただきありがとうございました。〇〇物件はいかがでしたでしょうか。ご質問がございましたらお気軽にどうぞ。`,
    mockOutputSecondary: `## 2. 社内共有メモ\n\n窓の結露について要確認。築年数・修繕履歴を次回共有。`,
    systemPrompt: "あなたは内見後フォローメールの下書きを生成するアシスタントです。",
    outputStructure: "顧客向け文面と社内共有メモの2セクションで出力すること。",
    sampleData: [
      "好印象。窓の結露が気になるとのこと。翌日フォローしたい",
      "価格交渉の意向あり。条件を整理して提案",
      "他物件と比較検討中。1週間後に再連絡",
    ],
    ctaTitle: "あなたのフォローフォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "内見反応からフォローメールと社内メモを即生成。追客を効率化します。",
    industryTags: ["不動産", "士業"],
    functionTags: ["追客", "文書生成"],
    moduleTags: ["LLM"],
    oneLiner: "内見反応からフォローメールを即生成",
  },
  {
    _type: "aiDemo" as const,
    title: "申し送り要点圧縮",
    slug: { _type: "slug" as const, current: "handover-points-compress" },
    industry: "legal",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "申し送りたい内容を入力してください",
    mockOutputPrimary: `## 1. 申し送り文\n\n- A様: 血圧安定。服薬確認済み\n- B様: 転倒リスクあり。見守り強化\n- C様: 家族面談希望。連絡待ち`,
    mockOutputSecondary: `## 2. 注意観察ポイント\n\nB様: 歩行時のふらつき。転倒予防のため環境整備を検討。`,
    systemPrompt: "あなたは申し送りの要点を圧縮するアシスタントです。",
    outputStructure: "申し送り文と注意観察ポイントの2セクションで出力すること。",
    sampleData: [
      "Aさん血圧安定。Bさん転倒の心配。Cさん家族が面談希望",
      "服薬確認済み。異常なし。明日の予定を共有",
      "入浴介助で注意。食事は問題なし",
    ],
    ctaTitle: "あなたの申し送りフォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "申し送り内容から要点と注意ポイントを即圧縮。記録業務を効率化します。",
    industryTags: ["医療", "介護"],
    functionTags: ["記録業務", "要約"],
    moduleTags: ["LLM"],
    oneLiner: "申し送り内容を要点に圧縮",
  },
  {
    _type: "aiDemo" as const,
    title: "遅延連絡テンプレ自動化",
    slug: { _type: "slug" as const, current: "delay-notice-template" },
    industry: "manufacturing",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "遅延の理由・状況を入力してください",
    mockOutputPrimary: `## 1. 顧客連絡文\n\nお世話になっております。〇〇便につきまして、〇〇のため〇時頃の配達となる見込みです。ご不便をおかけし申し訳ございません。`,
    mockOutputSecondary: `## 2. 社内配車メモ\n\n〇〇便: 遅延。理由〇〇。到着見込み〇時。`,
    systemPrompt: "あなたは遅延連絡のテンプレを自動生成するアシスタントです。",
    outputStructure: "顧客連絡文と社内配車メモの2セクションで出力すること。",
    sampleData: [
      "渋滞で30分遅れ。顧客に連絡したい",
      "車両トラブル。1時間遅延見込み",
      "積み忘れで再配送。午後に到着",
    ],
    ctaTitle: "あなたの連絡フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "遅延状況から顧客連絡文と社内メモを即生成。配送管理の連絡業務を効率化します。",
    industryTags: ["物流", "小売"],
    functionTags: ["配送管理", "文書生成"],
    moduleTags: ["LLM"],
    oneLiner: "遅延状況から連絡文を即生成",
  },
  {
    _type: "aiDemo" as const,
    title: "面接評価コメント整理",
    slug: { _type: "slug" as const, current: "interview-eval-comment" },
    industry: "legal",
    inputType: "text_only" as const,
    runMode: "mock_preview" as const,
    inputPlaceholder: "面接の所見・評価ポイントを入力してください",
    mockOutputPrimary: `## 1. 評価サマリ\n\n- 意欲: 高。志望動機が明確\n- 経験: 不足あり。成長意欲で補完可能\n- コミュニケーション: 良好\n- 総合: 採用推奨`,
    mockOutputSecondary: `## 2. 次回面接質問案\n\n1. 〇〇の経験を深掘り\n2. 入社後のキャリアイメージ\n3. 即戦力度の確認`,
    systemPrompt: "あなたは面接評価コメントを整理するアシスタントです。",
    outputStructure: "評価サマリと次回面接質問案の2セクションで出力すること。",
    sampleData: [
      "意欲高い。経験は浅いが成長意欲あり。採用推奨",
      "技術力は申し分なし。コミュニケーション要確認",
      "志望動機が弱い。2次で深掘りしたい",
    ],
    ctaTitle: "あなたの評価フォーマットに合わせた試作を3営業日で提出します。",
    ctaButtonText: "3営業日で試作デモを受け取る",
    description: "面接所見から評価サマリと次回質問案を即整理。採用業務を効率化します。",
    industryTags: ["人材", "士業"],
    functionTags: ["採用", "要約"],
    moduleTags: ["LLM"],
    oneLiner: "面接所見から評価コメントを即整理",
  },
];
